name: dvanille

description: Protótipo web/mobile da D'Vanille — versão Flutter fiel ao protótipo HTML

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: CreamCake
      fonts:
        - asset: assets/fonts/CreamCake.otf

  assets:
    - assets/images/logoreal.svg
    - assets/images/rodape.svg
    - assets/images/fachada_DVanille.png
    - assets/images/instalogo.svg
    - assets/images/cafeteriainterna.png
    - assets/images/bolo.svg
    - assets/images/salgado.svg
    - assets/images/doce.svg
    - assets/images/sobremesagelada.svg
    - assets/images/bebidaquente.svg
    - assets/images/bebidagelada.svg